import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :inventory_watcher, InventoryWatcherWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: InventoryWatcher.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# CORS for frontend (allow your frontend domain)
cors_origins =
  (System.get_env("FRONTEND_ORIGINS") ||
     System.get_env("FRONTEND_URL") ||
     "https://your-frontend-domain.com")
  |> String.split(",", trim: true)

config :cors_plug,
  origin: cors_origins,
  max_age: 86_400,
  methods: ["GET", "POST", "OPTIONS"]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
